### ISSUE TITLE
Wrong useContentfulLiveUpdates argument type

### ISSUE THREAD

**Issue by manuelrodgzz** [contentful/live-preview#119]
When I try to pass the entry I get from contentful I see the following error message. I made sure that I'm using the `Entry` type from contentful.

<img width="388" alt="image" src="https://github.com/contentful/live-preview/assets/56905268/aad8412e-83fe-4cc6-aff9-96d13863af62">
<img width="754" alt="image" src="https://github.com/contentful/live-preview/assets/56905268/211b1782-4431-4241-906a-81ea366a0ab6">

Next: 12.3.1
Contentful: 9.1.4
@contentful/live-preview: 2.1.1

**Comment by YvesRijckaert** [comment]
Hi @manuelrodgzz could you show me what you're trying to pass to the hook?
How do you get the entry from Contentful?

**Comment by himynameistim** [comment]
I get the same thing. My model is generated using cf-content-types-generator.

<img width="675" alt="image" src="https://github.com/contentful/live-preview/assets/5212530/ba6861cc-0478-4811-aed5-8b5dbfb676df">

<img width="465" alt="image" src="https://github.com/contentful/live-preview/assets/5212530/f00bd1b8-93f9-4a25-b187-7d2252dad94f">

**Comment by manuelrodgzz** [comment]
@YvesRijckaert I'm passing this object, which is an entry I got from the `getEntries` method from contentful.
<img width="641" alt="image" src="https://github.com/contentful/live-preview/assets/56905268/ce2a9d8a-6f4b-45b4-ba43-62121895a781">

**Comment by YvesRijckaert** [comment]
Hi both! This issue should be fixed once this gets released: https://github.com/contentful/live-preview/pull/126
