### ISSUE TITLE
Automatic updates not available for locale which uses a fallback locale

### ISSUE THREAD

**Issue by tomsaunders1882** [contentful/live-preview#140]
If a locale uses a fallback locale, then automatic updates are not possible. The update overrides the field as `null` rather than checking for the value of the field on a fallback locale:
https://github.com/contentful/live-preview/blob/main/src/helpers/field.ts#L24

**Comment by chrishelgert** [comment]
Hey,
thank you for reporting the issue, we will investigate that shortly

**Comment by t-saunders** [comment]
> Hey, thank you for reporting the issue, we will investigate that shortly

Hi @chrishelgert , any update on this?

**Comment by chrishelgert** [comment]
Hey,
no update yet, we're still working on a reliable solution here

**Comment by chrishelgert** [comment]
Hey,
we just released a new version 2.6.0 with support for fallback locale handling
