### ISSUE TITLE
Cannot read properties of null

### ISSUE THREAD

**Issue by tony-gutierrez** [contentful/live-preview#161]
I cannot get the live updates to work in Gatsby. The example for Gatsby does not use the common gatsby format, but I feel like I am passing in the correct info. The error I get is:

![image](https://github.com/contentful/live-preview/assets/15345331/155d9ef9-0934-41ac-b6f3-95bed89060d4)

My query is:
```
export const data = graphql`
    query($id: String!, $Lang: String!, $IndustryTaxonomies: [String!], $ServicesTaxonomies: [String!], $SolutionsTaxonomies: [String!], $LocationsTaxonomies: [String!]) {
        contentfulPage(id: { eq: $id }) {
            contentful_id
            node_locale
            internal {
                type
            }
            sys {
                contentType {
                    sys {
                        id
                    }
                }
            }
            seoAndMetadata {
                ...fContentfulSeoMetadata
            }
            body {
                raw
            }
           ...

            hero {
                ...fContentfulHeroes
            }

            components {
                ...fContentfulComponents         
            }
        }
  }`
```

And my component definition is:
```
const Item = ({ data }) => {
    const item = useContentfulLiveUpdates({
        ...data.contentfulPage,
        sys: { id: data.contentfulPage.contentful_id },
    });
    ...
}
```

**Comment by chrishelgert** [comment]
Hey,
thanks for reporting the issue, the `hero` and `components` in your queries are these references? (Entry, Asset)
They would also need the `sys.id` information for the matching, we know that it's currently a little bit confusing setting this up in Gatsby, but we're working on it 👍

**Comment by tony-gutierrez** [comment]
Spent a lot of time making a function that adds sys.id to everything, but same error.

**Comment by tony-gutierrez** [comment]
@chrishelgert I think the problem is that null is passing the object test in this line 613. It needs to test for null before testing for object type. 

![image](https://github.com/contentful/live-preview/assets/15345331/ef0a9b2f-f4e4-4225-9719-ac4f57bc3e96)

**Comment by chrishelgert** [comment]
Hey @tony-gutierrez,
is it working for you with the new version?
The code in your screenshot, should be the REST implementation, it could be possible that there is also a `__typename` missing somewhere on your data

**Comment by tony-gutierrez** [comment]
@chrishelgert I no longer get the error, but cannot get any content to update in the live preview.
I am not sure what you are referring to with the REST implementation, but this is a Gatsby site using gatsby-source-contentful

I have not seen any documentation around __typename or where it is required.

**Comment by chrishelgert** [comment]
We have an implementation for REST and one for GraphQL inside the SDK, if you use GraphQL every entry should have the `__typename` information on it, this information is essential for doing the updates.
We will have a look at the docs and try to optimize them.
For mentioning we discovered an additional issue with Gatsby, which we currently working on

**Comment by tony-gutierrez** [comment]
I'm confused...The REST vs Graphql option refers to what exactly? How you are retrieving data from contentful initially? 

I could include __typename, but it is going to be the __typename from **GATSBY's** Graphql, not Contentful's.

**Comment by YvesRijckaert** [comment]
Hi @tony-gutierrez 
Thank you for reporting this issue.
We have identified more issues with Gatsby, and are working on bringing better support for it. It seems like Gatsby is not using the Contentful GraphQL API and have their own GraphQL API to fetch content from Contentful. We don’t have a timeline for fixing it yet, but we have it in our backlog.
