### ISSUE TITLE
Cannot turn on LivePreview and InspectMode for Nextjs app

### ISSUE THREAD

**Issue by vadimnike** [contentful/live-preview#163]
I was trying to turn on LivePreview and InspectMode  in Contentful but it is not working at all for me.
Let me introduce steps what I did:
1) Imported _ContentfulLivePreviewProvider_ into **_app.js** and enable all needed props:
`import { ContentfulLivePreviewProvider } from '@contentful/live-preview/react';` 

<img width="1268" alt="Screenshot 2023-06-14 at 23 09 22" src="https://github.com/contentful/live-preview/assets/12830595/f53c4723-cebc-4973-8fcd-0eecd58912e5">

2) imported  _useContentfulLiveUpdates, useContentfulInspectorMode_to UI component in order to make it editable in livePreview mode:
`import {
  useContentfulLiveUpdates,
  useContentfulInspectorMode,
} from '@contentful/live-preview/react';`
<img width="1422" alt="Screenshot 2023-06-14 at 21 37 25" src="https://github.com/contentful/live-preview/assets/12830595/d7b08e0d-5645-40ae-b31f-442ae8769c09">
<img width="804" alt="Screenshot 2023-06-14 at 21 38 29" src="https://github.com/contentful/live-preview/assets/12830595/805d53f0-344e-41ab-bec3-5bd872a7e0bf">

3. After deploing my changes I always see that Live peview is not active in contetnful:
<img width="1775" alt="Screenshot 2023-06-14 at 23 02 28" src="https://github.com/contentful/live-preview/assets/12830595/17748e10-8413-4308-8bc8-2c0c5bccb387">
<img width="1775" alt="Screenshot 2023-06-14 at 21 44 19" src="https://github.com/contentful/live-preview/assets/12830595/f76fe767-1b04-468e-82cc-4a1b76b5c6f2">

**SAAG Page Title** field in left side was changed by adding text 'test' in the end but nothing happen in right side. InspectMode also not working.

Here is the package.json from app with current version of React, Nextjs, contentful and node:
<img width="556" alt="Screenshot 2023-06-14 at 23 17 53" src="https://github.com/contentful/live-preview/assets/12830595/022b2b58-7a3b-4b88-a872-d67527100b97">

Could someone help me where I was wrong in instructions above or what I missed in order to enable livePreviewMode and InspctMode for Nextjs app??

**Comment by chrishelgert** [comment]
Hey,
**for the inspectorMode** - it looks like you need to call it in line 490:
```
<SchoolTopper school={data} collectionId={collectionId} {...inspectorProps()} ...>
```

I would also suggest to provide the fieldId on the SchoolTooper and not inside the hook, then you can re-use the functionality to bind multiple field ;)

```
const inspectorProps = useContentfulInspectorMode({ entryId: 'YOUR_ENTRY_ID })

// ...

<SchoolTopper school={data} {...inspectorProps({ fieldId: 'YOUR_FIELD_ID' })} />
```

**For the live updates:**
Are you using the GraphQL API or the REST one?
Are you seeing any errors in the console after enabling the debug mode?

**Comment by vadimnike** [comment]
Hi @chrishelgert 
I updated my code as you mentioned for that page and for another one.
Nothing changed - I updated in left column title by adding 11 for testing but page in right side was not updated - inspectMode and liveUpdates still not working for me.
<img width="1593" alt="Screenshot 2023-06-21 at 14 34 40" src="https://github.com/contentful/live-preview/assets/12830595/4f2efe42-75f7-457b-9f55-5cc6800b54b9">

Maybe something wrong with dependencies in package.json?
Now I am using:
 node version 14.18.1
 react 17.0.2
 next 12.0.3

**Comment by YvesRijckaert** [comment]
In the screenshot you shared, you are using the slug as the entry id `(entryId: data.slug)`, can you try changing this to the actual entry id (should be in `data.sys.entryId`)?
You can have a look at our examples folder, we have an example with Next.js with the REST and GraphQL API
