### ISSUE TITLE
Rich text fields with hyperlink don't appear to work

### ISSUE THREAD

**Issue by nrandell** [contentful/live-preview#179]
If you've got a rich text field with a hyperlink, it is reported as 
```
links {
  entries {
    hyperlink {
      ... data for the hyperlink
    }
  }
}
```

But the live preview doesn't appear to support hyperlink, so when an update occurs, the hyperlink field is removed. I think it's all around this code https://github.com/contentful/live-preview/blob/e11dfe2627fb0eb9a1c6f91f4b4fc7d14eb6d04d/src/graphql/entries.ts#L174 and around `processRichTextField`

**Comment by chrishelgert** [comment]
Thank you for reporting the issue, we will have a look
