### ISSUE TITLE
Elements sometimes disappear in preview mode

### ISSUE THREAD

**Issue by j-quelly** [contentful/live-preview#183]
When we open preview mode and have live preview and inspector props enabled the UI elements will sometimes disappear.

Note that in this screenshot I have selected the h1 element which is not displaying in preview. Usually after clicking, resizing, or editing a few things it will appear again:

![Screenshot 2023-06-27 at 11 24 52 AM](https://github.com/contentful/live-preview/assets/10458851/db024c0d-a8b9-46fb-871e-5873f6a35173)

There should also be buttons beneath the text which are also missing

**Comment by z0al** [comment]
Hey, thank you for the report!

> UI elements will sometimes disappear.

This is going to be tricky to reproduce. Could you please submit a minimal reproducible example to help with the investigation? 

Feel free to use [CodeStandbox](https://codesandbox.com/) or any other similar service of your choosing.

**Comment by j-quelly** [comment]
@z0al it seems that the height of the element is set to `0` are you use a ref to calculate the element dimensions?

**Comment by j-quelly** [comment]
@z0al any updates here?

**Comment by j-quelly** [comment]
This seems resolved after updating to 2.6.0

**Comment by j-quelly** [comment]
This seems resolved after updating to 2.6.0
