### ISSUE TITLE
Nested elements not updating in live preview

### ISSUE THREAD

**Issue by sliktrik** [contentful/live-preview#197]
It appears that nested references don't update as you type while top level elements do

graphql query

```
query {
        pageCollection(where:{ slug:"${slug}" }, preview: true, limit: 1){
            items{
                sys{
                    id
                }
                title
                slug
                meta{
                    title
                    description
                    image{
                        ... on Asset{
                            url
                        }
                    }
                }
                components:componentsCollection{
                    all:items{
                        ... on HeroComponent{
                            __typename
                            sys{
                                id
                            }
                            title{
                                json
                            }
                            gallery:galleryCollection{
                                items{
                                  ... on Asset{
                                    url
                                  }
                                }
                            }
                        }
                        ... on MessageComponent{
                            __typename
                            sys{
                                id
                            }
                            msgtitle:title
                            description{
                                json
                            }
                            editor{
                                sys{
                                    id
                                }
                                title
                                name
                                avatar{
                                    url
                                }
                            }
                            button{
                                sys{
                                    id
                                }
                                label
                                location
                            }
                        }
                        ... on OfferingComponent{
                            __typename
                            sys{
                                id
                            }
                            featuretitle:title
                            featuresCollection(limit:9){
                                items{
                                    sys{
                                        id
                                    }
                                    title
                                    description
                                    icon{
                                        url
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
```

component 'MessageComponent'

```
import ErrorPage from 'next/error'
import { useRouter } from 'next/router'
import { documentToReactComponents } from '@contentful/rich-text-react-renderer'
import { BLOCKS, MARKS } from '@contentful/rich-text-types'
import { useContentfulInspectorMode, useContentfulLiveUpdates } from '@contentful/live-preview/react'

import styles from './offering.module.css'

export default function OfferingComponent(props) {

    const updatedProps = useContentfulLiveUpdates(props)
    const inspectorProps = useContentfulInspectorMode({ entryId: props.sys.id })
    const router = useRouter()
    const options = {}

    if (!router.isFallback && !updatedProps) {
        return <ErrorPage statusCode={404} />
    }

    return (
        <div className={styles.container}>
            <div className={styles.inner}>
                <h2 {...inspectorProps({ fieldId: 'featuretitle' })}>{updatedProps.featuretitle}</h2>
                <div className={styles.items}>
                    {updatedProps.featuresCollection.items.map((item, i) => (
                        <div className={styles.item} {...inspectorProps({ entryId: item.sys.id, fieldId: 'feature' })} key={i}>
                            <img {...inspectorProps({ entryId: updatedProps.featuresCollection.items[i].sys.id, fieldId: 'icon' })} 
                                src={updatedProps.featuresCollection.items[i].icon.url}
                            />
                            <h4 {...inspectorProps({ entryId: updatedProps.featuresCollection.items[i].sys.id, fieldId: 'title' })}>
                                {updatedProps.featuresCollection.items[i].title}
                            </h4>
                            <p  {...inspectorProps({ entryId: updatedProps.featuresCollection.items[i].sys.id, fieldId: 'description' })}>
                                {updatedProps.featuresCollection.items[i].description}
                            </p>
                        </div>
                    ))}
                </div>
            </div>
        </div>
    )
}
```

if you edit or change the value of 'featuretitle' in live preview it updates in realtime

If you edit or change the value of 'updatedProps.featuresCollection.items[i].title' in live preview it does not update in realtime

i should also note that if you click the 'refresh' icon 'updatedProps.featuresCollection.items[i].title' does update

**Comment by YvesRijckaert** [comment]
Hi! Thanks for submitting this bug report. Could you tell me which version you are running of the SDK? Could you update to the latest version?
Are these references inside of a rich text component? We recently fixed an issue that should update these

**Comment by sliktrik** [comment]
currently installed @contentful/live-preview@2.4.6

These references are not related to rich text but are a reference field type

**Comment by rafaelmusetti14** [comment]
I tried passing the query as a parameter to the hook but I'm getting an error on build. But in my case I'm using graphql from gatsby. Does the SDK support this as well? I'm having the same issue with nested elements not updating.

**Comment by YvesRijckaert** [comment]
We currently are still working on supporting Gatsby, since they are using a different GraphQL structure than our standard GraphQL API. There's an example in the examples directory, but only a few fields are working with live updates for now. Inspector mode should work fine

**Comment by brcaua** [comment]
Hi, have some updates about this? I'm trying to use this same approach but with the same issue.

**Comment by YvesRijckaert** [comment]
@brcaua Sorry I don't have an update yet, we are working on improving the SDK (and eventually adding support for Gatsby), so keep an eye out!

**Comment by dpatilctct** [comment]
@YvesRijckaert - We are currently using Gatsby4 with Contentful and React in our codebase, previously it was Gatsby2. Our preview is built with old package called as Contentfully https://github.com/nascentdigital/contentfully which is not working well after the upgrade to Gatsby4. Since you have mentioned above that Gatsby support is still under development, is there any other method by which we can build our own preview while the live updates SDK is made fully functional? Our content editors use Contentful preview for content change on a daily basis and we would like to get it fixed asap as it is causing a lot of inconvenience and discrepancies while previewing the content changes. Any alternate suggestions will be really helpful. Thank you!

**Comment by YvesRijckaert** [comment]
Hello @dpatilctct,

Unfortunately, I can't provide insights on the `Contentfully` plugin as we have not tested it yet with our live preview SDK. Our support for the default `gatsby-source-contentful` plugin is in the pipeline, mainly because it does not integrate with the official Contentful GraphQL API. The functionality of our live preview SDK is tailored to match the response format of the official Contentful GraphQL API.

Here's what we've noted so far when comparing the two:

- The `gatsby-source-contentful` obfuscates the `sys.id` and converts it into `contentful_id`.
- The rich text response format differs.
- Variations are also seen in long text fields (including the markdown editor), assets, and references.
- However, other fields, such as short text fields, should be functional as of now.

For the time being, a manual page refresh could serve as a temporary fix. Also, inspector mode should be fully functional with Gatsby. We're planning to extend our framework support in Q4. Keep an eye out for updates!

**Comment by dpatilctct** [comment]
Thank you @YvesRijckaert for the detailed insights on the comparison between the two, it's very helpful. We'll keep an eye out on the updates. Any chances we would have them by this year?
