### ISSUE TITLE
No Typescript types starting from version 2.4.6

### ISSUE THREAD

**Issue by emilsbee** [contentful/live-preview#199]
**Describe the bug**
Starting from version 2.4.6 there is no Typescript typing anymore.

**To Reproduce**
1. Install version 2.4.6 or 2.4.7 in a React based Typescript project
2. In VSCode try to view a type definition of for example the hook `useContentfulInspectorMode()` and it will show `any`

**Expected behavior**
Type definitions should be available

**Context:**
 - Live preview SDK version number: [2.4.6, 2.4.7]
 - REST (Using the JS SDK v10)

**Comment by chrishelgert** [comment]
Hey,
thanks for the feedback, we will have a look 👀

**Comment by emilsbee** [comment]
Everything works now. Thanks for solving it so quickly!
