### ISSUE TITLE
 Rich text embedded entry - Cloudinary asset JSON not returned in live preview

### ISSUE THREAD

**Issue by corybell** [contentful/live-preview#215]
**Describe the bug**
I have an Article content type with a Rich Text field which allows embedded entries.  I also have an Asset Wrapper content type with a JSON object field for Cloudinary assets (I followed the setup [guide](https://www.contentful.com/help/cloudinary-app/)).  If I have an embedded Asset Wrapper in an Article's rich text field and start changing the rich text, the Asset Wrapper's JSON field is no longer returned from `useContentfulLiveUpdates`.  The Article renders as expected initially.  The bug only happens after changing the rich text in live preview.

**Expected behavior**
Rich text embedded entries with JSON object fields should be returned correctly after the rich text has been changed.

**Context (please complete the following information):**
 - Live preview SDK version number: 2.4.11
 - GraphQL API
 - NextJS

**Comment by liviutodoran** [comment]
@corybell please could give me some insights  of how to implement the LivePreview for RichText ... 
I am not able with the docu and the examples https://github.com/contentful/live-preview/tree/main/examples/gatsby
I manage to do it with other custom components ...where we have `<p>{title}</p>` or `<div>{title}</div>` but not with <RichText/> 

Thank you

**Comment by zecka** [comment]
I got the same exact same issue

I got a "picture" field into my embedded entry "Image". Picture field is a cloudinary field.
This field is removed after passing by data into `useContentfulLiveUpdates` function

## Before useContentfullLiveUpdates
![image](https://github.com/contentful/live-preview/assets/18116930/216ec88f-d602-4cd3-a87e-7fe6ce7a3620)

## After useContentfullLiveUpdates
![image](https://github.com/contentful/live-preview/assets/18116930/5b2fdcd5-8201-4ef9-8b4a-1ed139e06b92)

**Comment by YvesRijckaert** [comment]
Hi @liviutodoran and everyone else who encountered this issue,

Firstly, I apologize for the delay in my response. Thank you for your patience. I've reviewed the issue, and the solution provided by @zecka is correct.

Here's a revised approach to render embedded nodes in your RichText:

We have our `RichText` component:
```typescript
export const RichText = ({
  doc,
  links,
}: RichTextProps): ReactElement | null => {
  if (!doc || !links) {
    return null;
  }

  const linkMap = buildLinkMap(links);

  const options = {
    renderNode: {
      [BLOCKS.EMBEDDED_ENTRY]: (node: Node) =>
        renderEmbeddedNode(node, linkMap, "Block embedded entry"),
      [INLINES.EMBEDDED_ENTRY]: (node: Node) =>
        renderEmbeddedNode(node, linkMap, "Inline embedded entry"),
      [INLINES.ENTRY_HYPERLINK]: (node: Node) =>
        renderEmbeddedNode(node, linkMap, "Entry hyperlink"),
    },
  };

  return (
    <div>
      {documentToReactComponents(doc, options)}
    </div>
  );
};
```

And the function that renders the embedded entries in rich text:
```typescript
const renderEmbeddedNode = (node: Node, linkMap: any, type: string) => {
  const { id } = node.data.target.sys;

  const linkedEntry = linkMap[id];
  if (!linkedEntry) return null;

  const entry = useContentfulLiveUpdates({ ...linkedEntry });

  return (
    <div style={styles.container}>
      <i style={styles.typeIndicator}>{type}</i>
      {Array.isArray(entry?.jsonObject) &&
        entry.jsonObject.map((cloudinaryAsset) => (
          <img
            key={cloudinaryAsset.url}
            style={styles.img}
            src={cloudinaryAsset.url}
          />
        ))}
    </div>
  );
};
```


The key here is in how the `renderEmbeddedNode` function has been structured, ensuring that the `useContentfulLiveUpdates` hook fetches the updated data for each embedded entry.

Here is a video demo that shows this solution:

https://github.com/contentful/live-preview/assets/22968325/2b8814cb-44c2-4b25-a846-9c0c42f081b2


I hope this helps!

**Comment by YvesRijckaert** [comment]
@liviutodoran You mention using Gatsby, but currently Gatsby support is still under development. So it might not work out of the box.

**Comment by corybell** [comment]
@YvesRijckaert @zecka Thanks for the replies.  I was hoping to keep all live update logic outside of my production rich text rendering code.  With this solution, it doesn't look possible.  Is there a way to keep `useContentfulLiveUpdates` calls outside of the rich text rendering?  Two separate rich text rendering paths - one for prod and one for preview?   Or is it a non-issue?

**Comment by zecka** [comment]
@corybell Do you have separate build for preview on prod right ?

**Comment by YvesRijckaert** [comment]
@corybell Not sure if I understand it correctly, but you can setup that live preview code only gets provided in the draft Mode of Next.js (you can do this configuration where you set up the provider, probably `_app.tsx`)

```typescript
function App({ Component, pageProps }: AppProps) {
  return (
    <ContentfulLivePreviewProvider
      locale="en-US"
      enableInspectorMode={pageProps.draftMode} //only enable in draft mode
      enableLiveUpdates={pageProps.draftMode}  //only enable in draft mode
    >
      <Component {...pageProps} />
    </ContentfulLivePreviewProvider>
  );
}
```
