### ISSUE TITLE
Add a vanilla JS example

### ISSUE THREAD

**Issue by groenroos** [contentful/live-preview#217]
Could an example project please be provided in the `./examples` folder for a complete vanilla JS implementation? Each implementation in there currently seems to use React.

Alternatively (or ideally additionally) the documentation for the vanilla JS approach could be expanded, as the code examples provided include multiple undefined variables (`id`, `title`, `data`, etc) with no explanation what they are, where they should come from, or what they should contain.

Related to #152

**Comment by cachrisman** [comment]
I agree that the [Vanilla JS documentation](https://github.com/contentful/live-preview#vanilla-javascript) in the README is lacking, but here's what I've been able to figure out:

Before you initialize the live preview you'll want to make whatever call (Content Preview API or Content GraphQL API) to get the entries and assets that make up the page being requested. Then for each entry+field on which you want to use the inspector mode to show an edit button in the preview you'll need to run `ContentfulLivePreview.getProps({ entryId: id, fieldId: title });` and then also `ContentfulLivePreview.subscribe({data, locale, callback});` to get updates when a field is edited in Contentful. 

- `id` is the entry ID
- `data` is the JSON response from the CPA for an entry/asset or an array of entries (or assets)
- `callback` is a function to be called when the entry/asset is updated in Contentful to tell the frontend/live preview to update the rendering. The callback is what makes the frontend update almost instantaneously when typing in a field in the editor.

I hope this is helpful!!

**Comment by dreysolano** [comment]
Another issue to note is that older projects that use Webpack 4 will encounter build failures for both latest `contentful` (v10.4.1) and `@contentful/live-preview` packages, both requires adding `babel-loader` to your Webpack config. The below is for a Nuxt2 project, but should provide the basis for what you'll need.

```
config.module.rules.push({
  test: /\.[cm]?js$/,
  exclude: /node_modules\/(?!(contentful\/dist|@contentful\/live-preview)\/).*/,
  use: {
    loader: 'babel-loader',
    options: {
      presets: [
        [
          '@babel/preset-env',
          {
            targets: {
              browsers: ['last 2 versions', 'ie >= 11'],
            },
          },
        ],
      ],
      plugins: ['@babel/plugin-proposal-class-properties'],
    },
  },
})
```

The @babel/plugin-proposal-class-properties dependency is required for a `contentful@10.4.1` issue around static class properties. Note that I also had to use a negative lookahead assertion in the exclude regex to include the necessary package files for transpiling. Hope this helps.
