### ISSUE TITLE
Couldn't find package "@contentful/visual-sdk@^1.0.0-alpha.1"

### ISSUE THREAD

**Issue by Bartoszkie** [contentful/live-preview#219]
**Describe the bug**
Hello!
I'm using Next.js and Contentful for my project, and today I wanted to spin on the Live-Preview feature. Unfortunately, I ran into an unexpected wall which is impossible even to install the package needed for that.

**To Reproduce**
1. Make sure you have the Node >= 16 (I'm using the Node v18)
2. Try to run the following command: `yarn add @contentful/live-preview`

**Expected behavior**
Package successfully installed. 

**Screenshots / example**
<img width="1333" alt="image" src="https://github.com/contentful/live-preview/assets/34746175/46880028-01e2-4a9d-ad45-3828ba9f6091">

**Context (please complete the following information):**
- contentful: "^10.3.4",
- contentful-management: "^10.39.1",
- contentful-sdk-core: "^7.1.0",
 - GraphQL API to fetch data from Contentful

**Additional context**
By looking at the repo, and the recent updates, I think there is an issue with that particular change: [link here](https://github.com/contentful/live-preview/commit/d03518468b009fa07635ff16064e15b7d6234cb7).

**Comment by chrishelgert** [comment]
Hey,
thanks for reporting - I will look at it

**Comment by chrishelgert** [comment]
Hey,
sorry for the inconvenience - it was published as a private module.
It's now changed to public and you should be able to access it 
https://www.npmjs.com/package/@contentful/visual-sdk

**Comment by Bartoszkie** [comment]
Hey @chrishelgert, that worked, thanks a lot! This issue can be closed now.
