### ISSUE TITLE
Using provider breaks the page

### ISSUE THREAD

**Issue by andrisole92** [contentful/live-preview#230]
**Describe the bug**

Adding `ContentfulLivePreviewProvider` broke the page.

**To Reproduce**

1. Install the package
2. Add `ContentfulLivePreviewProvider` to the page
3. Reload page
4. See the error

https://legacy.reactjs.org/docs/error-decoder.html/?invariant=321

**Expected behavior**
Expect page to load

**Screenshots / example**

<img width="1290" alt="Screenshot 2023-07-18 at 2 05 48 PM" src="https://github.com/contentful/live-preview/assets/17086705/74292bd4-edbd-4a22-946d-febe5a98d933">
<img width="531" alt="Screenshot 2023-07-18 at 2 05 43 PM" src="https://github.com/contentful/live-preview/assets/17086705/5f3cdd05-4618-43ac-913a-0b5d5cfa06d5">

**Context (please complete the following information):**
 - Live preview SDK version number: 2.4.0, 2.5.3

**Additional context**
N/A

**Comment by chrishelgert** [comment]
Hey,
thanks for reporting the issue, which react version are you using?
I just tried it out with this [example](https://github.com/contentful/live-preview/tree/main/examples/nextjs-rest) and it looked fine.
Have you tried running in it development mode for more information?

**Comment by andrisole92** [comment]
Hi @chrishelgert , 

Thank you for your response!

We are using React version 16.14.0.

I am running it in development mode and it's giving me this error immediately after I add the provider: https://legacy.reactjs.org/docs/error-decoder.html/?invariant=321

Also, we are using Snowpack, and I am not exactly sure what is causing the issue.

**Comment by YvesRijckaert** [comment]
Can you try to upgrade to react v17? It's part of our requirements: https://github.com/contentful/live-preview#requirements
