### ISSUE TITLE
Request to preview content is canceled

### ISSUE THREAD

**Issue by j-quelly** [contentful/live-preview#242]
**Describe the bug**
Request to preview service is showing canceled

**To Reproduce**
1. Go to content entry
2. Click on live preview
3. See error

**Expected behavior**
Live preview should show

**Screenshots / example**

![Screenshot 2023-07-27 at 4 59 36 PM](https://github.com/contentful/live-preview/assets/10458851/df4c2431-dec8-4893-ab68-2dbc8bfef743)

**Context (please complete the following information):**
 - We are not yet using the live preview component, it was working without it, not it does not seem to work

**Additional context**

**Comment by YvesRijckaert** [comment]
Hi @j-quelly 
Did you modify your website security configuration? See our docs: https://www.contentful.com/developers/docs/tutorials/general/live-preview/#requirements

If live preview was working before, can you share the preview URL here? thank you!

**Comment by j-quelly** [comment]
@YvesRijckaert as far as I know we have not changed any security headers, but I am looking into this.

I can share the preview link, but it will not resolve for you since you need to be connected to our VPN http://localhost:8001/api/preview/?id=0RKlEZkK5co6OIrxO7aKA

**Comment by j-quelly** [comment]
@YvesRijckaert here are the headers 
![Screenshot 2023-07-31 at 9 27 42 AM](https://github.com/contentful/live-preview/assets/10458851/bdd773f5-e048-435a-a4b8-2f83f0e8d819)

**Comment by YvesRijckaert** [comment]
Can you double check the preview URL? Our preview validation API ignores localhost URLs so they should always pass the check. Make sure you selected the correct preview platform before opening live preview.
Either way, we are working on adding a bypass for the preview validation

**Comment by j-quelly** [comment]
@YvesRijckaert Can you elaborate on what you mean by preview validation? And is their an ETA for this update?

**Comment by YvesRijckaert** [comment]
![image](https://github.com/contentful/live-preview/assets/22968325/bdf85f68-af39-4b3f-a153-3e66664e6f9a)
Our endpoint validates if the security headers are set correctly and shows a custom error message. We have now added a link to bypass this screen.
