### ISSUE TITLE
Flaky element rendering (elements do not render or are missing data)

### ISSUE THREAD

**Issue by j-quelly** [contentful/live-preview#252]
**Describe the bug**
Elements disappear in live preview

**To Reproduce**
1. Go to a Contentful entry
2. Click on live preview button
3. Scroll down 
4. See elements are not rendering

**Expected behavior**
Elements should render. Additionally it seems that some of the data will be missing from the copy of props. `const props = useContentfulLiveUpdates(staticProps);` which is maybe why the elements are not rendering. Upon upgraded to version `2.6.0` we've found that our components that _should_ have all the data defined in the response form contentful are throwing errors due to missing properties. This is not present when not using `useContentfulLiveUpdates()`

**Screenshots / example**
![Screenshot 2023-08-01 at 2 23 25 PM](https://github.com/contentful/live-preview/assets/10458851/338b5c34-d6ff-4969-9f12-673178662bc1)

![Kapture 2023-08-01 at 14 25 18](https://github.com/contentful/live-preview/assets/10458851/db333011-3122-4114-9812-c1c1c1dbf0a2)

**Context (please complete the following information):**
 - Live preview SDK version number: `"@contentful/live-preview": "^2.6.0",`
 - REST for querying data

**Additional context**
We're hoping to launch some major changes to our internal customers in the next 8 business days. Can this be resolved before then?

**Comment by chrishelgert** [comment]
Hey 👋 
Could you try version 2.6.2?
There is a limitation for how deep entries are resolved, and we increased it with the latest version

**Comment by j-quelly** [comment]
@chrishelgert 2.6.2 seems to still have the same problem

**Comment by chrishelgert** [comment]
Hey @j-quelly,
Could you open a support ticket at contentful please?
Then we have more possibilities for debuging and fixing this issue

**Comment by j-quelly** [comment]
@chrishelgert opened a ticket. Thanks!
