### ISSUE TITLE
NextJS + GraphQL: useContentfulLiveUpdates returns old data

### ISSUE THREAD

**Issue by sunehinz** [contentful/live-preview#265]
When using the `useContentfulLiveUpdates` hook with initial data and passing it a GraphQL query (DocumentNode) the hook returns the initial data on every update.

**Screenshots / example**
<img width="1988" alt="Screenshot 2023-08-10 at 23 12 00" src="https://github.com/contentful/live-preview/assets/25770935/25021359-fe2f-498d-8024-bc26fbd23f6d">

**Context (please complete the following information):**
 - Live preview SDK version number: 2.7.1
 - GraphQL API
 - React 18.2.14
 - NextJS 13.4.9
 - [graphql-request](https://github.com/jasonkuhrt/graphql-request) 6.1.0
 - [graphql-tag](https://github.com/apollographql/graphql-tag) 2.12.6

**Additional context**
I'm fetching the data in `getServerSideProps` and passing the query and result to the client. The `useContentfulLiveUpdates` hook is given the result as initial data and the query in the options. 

With the `debugMode` turned on in `ContentfulLivePreviewProvider` I can see updates are registered but even in the messages in console, the data recieved are the initial data. If I click on the "Refresh page" button the page is correctly updated.

* *page.tsx**
```typescript
export const getServerSideProps: GetServerSideProps = async (context) => {
  const testQuery = gql`
    query Frontpage {
      frontpage(id: "7DyhlXleGiQ8SNvxKBfmaM") {
        __typename
        sys { id }
        internalName
        url
      }
    }
  `
  const testResponse = await request(process.env.CTF_API_ENDPOINT || '', testQuery, {}, {
    'Authorization': `Bearer ${process.env.CTF_API_TOKEN || ''}`,
    'Content-Type': 'application/json'
  }) as { [key: string]: any }

  return {
    props: {
      testQuery: JSON.parse(JSON.stringify(testQuery)), // Required for NextJS to serialize the data
      testResponse,
    }
  }
}

const Frontpage: NextPageWithLayout = (props: FrontpageProps) => {
  const test = useContentfulLiveUpdates(props.testResponse, { query: props.testQuery })
  useEffect(() => { console.log(test) }, [test])

  return (
    ...
  )
}
```

**Comment by 2wce** [comment]
hi @sunehinz thank you for bringing this up. Can you please show me how you have setup the `ContentfulLivePreviewProvider`?

**Comment by sunehinz** [comment]
Sure!

```Typescript
import Head from 'next/head'
import { NextPage } from 'next'
import type { AppProps } from 'next/app'
import { ReactElement, ReactNode } from 'react'
import { ContentfulLivePreviewProvider } from '@contentful/live-preview/react'

import '../styles/globals.css'

export type NextPageWithLayout<P = any, IP = P> = NextPage<P, IP> & {
  getLayout?: (page: ReactElement, pageProps: BaseProps & { [key: string]: any }) => ReactNode
}

type AppPropsWithLayout = AppProps & { Component: NextPageWithLayout } & { pageProps: { [key: string]: any } }


export default function App({ Component, pageProps }: AppPropsWithLayout) {
  return (
    <>
      <Head>
        ...
      </Head>
      <ContentfulLivePreviewProvider
        locale="en-US" // Required: allows you to set the locale once and have it reused throughout the preview.
        enableLiveUpdates={process.env.CTF_LIVE_UPDATES === 'true'} // Optional: allows you to toggle live updates which are on by default.
        enableInspectorMode={process.env.CTF_INSPECTOR_MODE === 'true'} // Optional: allows you to toggle inspector mode which is on by default.
        debugMode={process.env.CTF_DEBUG_MODE === 'true'} // Optional: allows you to toggle debug mode which is off by default.
      >
        ...
          {Component.getLayout
            ? Component.getLayout(<Component {...pageProps} />, pageProps)
            : <Component {...pageProps} />
          }
        ...
      </ContentfulLivePreviewProvider>
    </>
  )
}

```

**Comment by YvesRijckaert** [comment]
@sunehinz Does the same thing happen when you don't supply the GraphQL query to the hook?
```
const test = useContentfulLiveUpdates(props.testResponse,)
```

**Comment by YvesRijckaert** [comment]
If the previous suggestion doesn't work, could you please submit a minimal reproducible example to help with the investigation?

Feel free to use [CodeStandbox](https://codesandbox.com/) or any other similar service of your choosing.

**Comment by sunehinz** [comment]
Created a minimal example at [CodeSandbox](https://codesandbox.io/p/github/DK-Company/contentful-live-preview-bug/master?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cllam7jw5000h2e6fn4kjupz7%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cllam7jw5000c2e6fz6cla8tv%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cllam7jw5000g2e6fqi7hem7s%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cllam7jw5000e2e6ffo439whn%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cllam7jw5000c2e6fz6cla8tv%2522%253A%257B%2522id%2522%253A%2522cllam7jw5000c2e6fz6cla8tv%2522%252C%2522activeTabId%2522%253A%2522cllam8tga01ec2e6fqd2uxtdo%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cllam7jw5000b2e6fw9biunuz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.env.example%2522%252C%2522id%2522%253A%2522cllam8tga01ec2e6fqd2uxtdo%2522%252C%2522mode%2522%253A%2522temporary%2522%257D%255D%257D%252C%2522cllam7jw5000e2e6ffo439whn%2522%253A%257B%2522id%2522%253A%2522cllam7jw5000e2e6ffo439whn%2522%252C%2522activeTabId%2522%253A%2522cllam7we8010c2e6fzerpt190%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522cllam7we8010c2e6fzerpt190%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252Fda-dk%2522%257D%255D%257D%252C%2522cllam7jw5000g2e6fqi7hem7s%2522%253A%257B%2522id%2522%253A%2522cllam7jw5000g2e6fqi7hem7s%2522%252C%2522activeTabId%2522%253A%2522cllam7uvh00p02e6fiurkz1o1%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cllam7jw5000f2e6fbof59y69%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cllam7k09000ud6g3aw3rhqbn%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522cllam7uvh00p02e6fiurkz1o1%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D).

Please note that:
- I did not provide an endpoint and token in the .env file
- The page to display changes are at /da-dk

**Comment by YvesRijckaert** [comment]
@sunehinz I can't open the project, maybe a permission issue?

**Comment by sunehinz** [comment]
> @sunehinz I can't open the project, maybe a permission issue?

My mistake. I've updated the link above to point towards the correct [CodeSandbox](https://codesandbox.io/p/sandbox/github/DK-Company/contentful-live-preview-bug/tree/master).

**Comment by YvesRijckaert** [comment]
Hi @sunehinz I was able to check out your project thanks!
It seems like we have an issue when the graphQL Query gets provided to the `useContentfulLiveUpdates` hook. If you remove the query, then the live updates are working correctly. I added a ticket in my teams backlog to have a further look at the issue. If you are not using graphQL aliasing, then you can continue using live preview without providing the query to the hook.
I will close this issue now but will keep you updated when we release a fix.

```typescript
import { NextPageWithLayout } from "../_app";
import { GetServerSideProps } from "next";
import { DefaultLayout } from "@/layouts";
import { useContentfulLiveUpdates } from "@contentful/live-preview/react";
import { request } from "graphql-request";
import { DocumentNode } from "graphql";
import gql from "graphql-tag";
import { useEffect } from "react";

type FrontpageProps = {
  testQuery: DocumentNode;
  testResponse: any;
};
const query = gql`
  query Frontpage {
    frontpage(id: "XlM2YC2DSAQa7903jEuVg", preview: true) {
      __typename
      sys {
        id
      }
      internalName
      url
    }
  }
`;

export const getServerSideProps: GetServerSideProps = async (context) => {
  const testResponse = (await request(
    process.env.CTF_API_ENDPOINT || "",
    query,
    {},
    {
      Authorization: `Bearer ${process.env.CTF_API_TOKEN || ""}`,
      "Content-Type": "application/json",
    }
  )) as { [key: string]: any };

  return {
    props: {
      testResponse,
    },
  };
};

const Frontpage: NextPageWithLayout = (props: FrontpageProps) => {
  //do not provide the GraphQL query to the hook for now...
  const test = useContentfulLiveUpdates(props.testResponse);

  useEffect(() => {
    console.log("updated data", test);
  }, [test]);

  return <div>{test.frontpage.internalName}</div>;
};

Frontpage.getLayout = DefaultLayout;
export default Frontpage;

```

**Comment by YvesRijckaert** [comment]
Fixed as part of https://github.com/contentful/live-preview/pull/288
