### ISSUE TITLE
Live preview not updating order of entities 

### ISSUE THREAD

**Issue by remcolakens** [contentful/live-preview#266]
**Describe the bug**
I have just implemented the `live-preview` mode into my Remix app version `1.19.1`. Below is my current implementation of the homepage:

_index.tsx
```typescript
import { gql } from '@apollo/client';
import { useContentfulLiveUpdates } from '@contentful/live-preview/react';

export async function loader({ context }: LoaderArgs) {
    const { data } = await context.apolloClient.query({
        query: gql(GET_CONTENT_BY_ID),
        variables: {
            id: '7tqHhUKldO14eJm4aiAOdA',
            preview: true,
        },
    });
    
    const contentfulItems = data
    ? data?.entryCollection?.items[0]?.pageContentCollection?.items
    : undefined;
    
    return {
        contentful: contentfulItems,
    };
}

export default function Homepage() {
    const { contentful } = useLoaderData<typeof loader>();
    const contentfulData = useContentfulLiveUpdates(contentful, {
        query: gql(GET_CONTENT_BY_ID),
    });
    ...
    <ContentfulComponent data={contentfulData} />
    ...
}
```

GET_CONTENT_BY_ID.ts
```graphql
export const GET_CONTENT_BY_ID = `
query getContentById($id: String!, $preview: Boolean) {
  entryCollection(where: { sys: { id: $id } }, preview: $preview) {
    items {
      ... on Homepage {
        pageContentCollection(limit: 25) {
          items {
            ...HeroBlockFragment
          }
        }
      }
    }
  }
}
${HERO_BLOCK_FRAGMENT}
` as const;
```

This setup renders the data on the homepage correctly, and live editing of the content is also functional. However, when I have multiple instances of `HeroBlockFragment` on my page and I attempt to change their order (for instance, moving block1 to the bottom), the updates are not reflected anymore.

**Expected behavior**
The entities' order should be respected and updated each time a change is made.

**Screenshots / example**

![Screen Recording 2023-08-11 at 10 50 22](https://github.com/contentful/live-preview/assets/2558163/2e15437b-cfed-40fc-8c33-8608bf79f903)

**Context (please complete the following information):**
 - Live preview SDK version number: 2.7.1
 - GraphQL API: 16.7.1
 - Remix: 1.19.1
 - Apollo/client: 3.7.17 (memory caching off)

**Additional context**
I conducted extensive debugging and found that the "PATCH" call in the network tab successfully updates the order. However, the associated hook does not trigger, resulting in no re-render.

![Screenshot 2023-08-11 at 10 47 58](https://github.com/contentful/live-preview/assets/2558163/e6411286-0d34-45dc-8c26-04ed696a95c6)

Manually running the query updates the order, and refreshing the page also resolves the issue.

**Comment by YvesRijckaert** [comment]
Hi @remcolakens
Thank you for submitting this bug report! I tried to reproduce your issue, using our Remix example (https://github.com/contentful/live-preview/tree/main/examples/remix). However, I am unable to do so 🤔

This is what I have in the `$slug.tsx` file:

```typescript
type QueryResponse = {
  postCollection: {
    items: Post[];
  };
};

type Embed = {
  __typename: string;
  sys: {
    id: string;
  };
  title: string;
};

type Post = {
  __typename: string;
  sys: {
    id: string;
  };
  multiRefCollection: {
    items: Embed[];
  };
};

type LoaderData = {
  post: Post;
  preview: boolean;
};

const getPostQuery = gql`
  fragment EmbedFragment on Embed {
    __typename
    sys {
      id
    }
    title
  }

  query Post($slug: String!, $preview: Boolean!) {
    postCollection(where: { slug: $slug }, limit: 1, preview: $preview) {
      items {
        ... on Post {
          __typename
          sys {
            id
          }
          title
          description
          multiRefCollection(limit: 25) {
            items {
              ...EmbedFragment
            }
          }
        }
      }
    }
  }
`;

export const loader: LoaderFunction = async ({ params, request }) => {
  const { slug } = params;

  const preview = await isPreviewMode(request);

  const API_TOKEN = preview
    ? process.env.CONTENTFUL_PREVIEW_ACCESS_TOKEN
    : process.env.CONTENTFUL_ACCESS_TOKEN;

  const data = (await contentful.request(
    getPostQuery,
    { slug, preview },
    { authorization: `Bearer ${API_TOKEN}` }
  )) as QueryResponse;

  const post = data.postCollection.items[0];

  return json({
    post,
    preview,
  });
};

export default function PostDetailPage() {
  const { post, preview } = useLoaderData<LoaderData>();
  const updatedPost = useContentfulLiveUpdates(post);

  return (
    <>
      {preview && <PreviewBanner />}
      <div>
        {updatedPost.multiRefCollection.items.map((embed) => (
          <p>{embed.title}</p>
        ))}
      </div>
    </>
  );
}
```

- I created a fragment, like in your example.
- I also have multiple instances of the same content type in my multi ref field ("Embed")
- I am using `graphql-request` instead of `@apollo` but I doubt that is causing the issue

Can you try to add `sys.id` and `__tyepname` to your GraphQL query? This has to be added for each content type you fetch with GraphQL, so the SDK knows what to update.

**Comment by YvesRijckaert** [comment]
@remcolakens Are you using GraphQL aliasing in the `HeroBlockFragment`? If not, can you try to remove the query as a parameter to the hook?
Instead of:
```
const contentfulData = useContentfulLiveUpdates(contentful, {
    query: gql(GET_CONTENT_BY_ID),
});
```

Try this:
```
const contentfulData = useContentfulLiveUpdates(contentful);
```


If that doesn't work, could you also try to reproduce your issue using the Remix example? https://github.com/contentful/live-preview/tree/main/examples/remix

**Comment by remcolakens** [comment]
I also tried replacing `apolloClient` with `GraphQLClient` but as already expected it had no impact whatsoever

**Comment by YvesRijckaert** [comment]
I think the only thing I changed from the example is updating the package version, does that make it work again?
I still can't seem to reproduce. Could you maybe submit a minimal reproducible example to help with the investigation?

Feel free to use [CodeStandbox](https://codesandbox.com/) or any other similar service of your choosing.

**Comment by remcolakens** [comment]
Seems like I've found the issue!

Here in the loader, I'm defining the `contentfulItems` variable
```typescript
export async function loader({ context }: LoaderArgs) {
  const { data } = await context.apolloClient.query({
    query: gql(GET_CONTENT_BY_ID),
    variables: {
      id: 'iXuNz0StVggCoxASxODRe',
      preview: true,
    },
  });
  
  const contentfulItems = data
    ? data?.entryCollection?.items[0]?.pageContentCollection?.items
    : undefined;

  return {
    contentful: contentfulItems,
  };
}

export default function Homepage() {
  ...
  return (
    {contentfulData?.map((item: IDataItem) => (
      <ContentfulComponent key={item.sys.id} item={item} />
    ))}
  )
}
```

Since the loader is being executed on the server it will only happen once, meaning that client-side stuff will not end up here. Moving the logic into my app seems to have solved the issue:

```typescript
export default function Homepage() {
      {contentfulData?.map((item: IDataItem) => (
        <ContentfulComponent key={item.sys.id} item={item} />
      ))}
}

export async function loader({ context }: LoaderArgs) {
  ...
  const contentfulItems = data ? data?.entryCollection?.items[0] : undefined;
}
  
  export default function Homepage() {
    ...
    return (
      {contentfulData?.pageContentCollection?.items.map((item: IDataItem) => (
        <ContentfulComponent key={item.sys.id} item={item} />
      ))}
    )
  }

```

Seems like it was a specific issue for Remix, but might be good to mention in the documentation that these data manipulations should not be done in the loader. Thanks for the code snippet @YvesRijckaert that made me look into the right place for debugging this.

Happy friday!
