### ISSUE TITLE
Live Preview SDK in next.js not updating. Failed to apply live update, Error: Unknown reference ...

### ISSUE THREAD

**Issue by Hultner** [contentful/live-preview#311]
**Describe the bug**

I'm not able to get live updates working in next.js. I've added the context provider, I've removed all content transformation from server side (markdown rendering) I use the hook but I keep getting reference errors. I've added the headers to next.config.js.

**To Reproduce**
1. Go to live preview for an article
2. Update the content
3. Content isn't updated without manual refresh

**Expected behavior**
Content should be live updated by the contentful hook.

**Screenshots / example**
If applicable, add screenshots to help explain your problem. Please also submit a minimal reproducible example to help with the investigation. Feel free to use CodeStandbox or any other similar service of your choosing.

Here's a screenshot showing the console output on contentful.
<img width="1536" alt="image" src="https://github.com/contentful/live-preview/assets/2669034/5f90f599-e419-471b-a33a-ab47b410bda7">

**Context (please complete the following information):**
 - Live preview SDK version number: 2.9.6
 - REST / GraphQL API [Which API are you using to query data from Contentful?]: REST (via contentful js client, run on server side using getServerSideProps).

**Additional context**
I haven't used inspector mode, I'm just trying to get live preview up. I have not provided any access tokens to the live preview context client side, but I can't find any documentation or examples doing so, so I suppose this is how it should work?

**Comment by YvesRijckaert** [comment]
Hi @Hultner Thank you for submitting this bug report.

Did you see that we have multiple Next.js examples in the [examples directory](https://github.com/contentful/live-preview/tree/main/examples)? Is there anything different in the setup between these examples and your code?

Without seeing your code, I won't be able to help. Could you maybe submit a minimal reproducible example to help with the investigation?
Feel free to use [CodeStandbox](https://codesandbox.com/) or any other similar service of your choosing.

**Comment by Hultner** [comment]
I used the next.js-rest example, I’ve compared my implementation to that
and can not find any differences in how the sdk and client is used, the
config also looks the same.

**Comment by Hultner** [comment]
I tried CodeSandbox but it's not letting me create any directories or files (logged in via github).

I can paste relevant configuration/code here as a minimal example.

pages/_app.js
```jsx
import { ContentfulLivePreviewProvider } from "@contentful/live-preview/react";

export default function CirculateApp({ Component, pageProps }) {
  return (
    <ContentfulLivePreviewProvider
      locale="en-GB"
      debugMode={true}
      enableLiveUpdates={true}
    >
      <Component {...pageProps} />
    </ContentfulLivePreviewProvider>
}
```

I created a separate preview file to simplify when developing which always runs in preview mode. Removed some types for brevity.

pages/articles/preview/[slug.tsx]
```tsx
import * as contentful from "contentful";
import { useContentfulLiveUpdates } from "@contentful/live-preview/react";
import { documentToReactComponents } from "@contentful/rich-text-react-renderer";

const CONTENTFUL_SPACE_ID = process.env.NEXT_PUBLIC_CONTENTFUL_SPACE_ID;
const CONTENTFUL_ACCESS_TOKEN = process.env.CONTENTFUL_ACCESS_TOKEN;
const CONTENTFUL_PREVIEW_TOKEN = process.env.CONTENTFUL_PREVIEW_TOKEN;

export function setupContentful(
  preview: boolean = false
): contentful.ContentfulClientApi<"WITHOUT_UNRESOLVABLE_LINKS"> {
  if (
    !CONTENTFUL_SPACE_ID ||
    !CONTENTFUL_ACCESS_TOKEN ||
    !CONTENTFUL_PREVIEW_TOKEN
  ) {
    throw new Error(
      "Please provide CONTENTFUL_SPACE_ID, CONTENTFUL_PREVIEW_TOKEN and CONTENTFUL_ACCESS_TOKEN env variables"
    );
  }
  const client = contentful.createClient({
    space: CONTENTFUL_SPACE_ID,
    accessToken: preview ? CONTENTFUL_PREVIEW_TOKEN : CONTENTFUL_ACCESS_TOKEN,
    ...(preview && { host: "preview.contentful.com" }),
  });
  return client.withoutUnresolvableLinks;
}

export default function BlogArticle({
  article,
}){
  const articleUpdated = useContentfulLiveUpdates(article);
  if (!articleUpdated) return "Loading…";
  const articleUpdated = useContentfulLiveUpdates(article);
  return (
    <>
      <h1>{article.fields.title}</h1>
      {article.fields.introduction &&
        documentToReactComponents(article.fields.introduction)}
    <>
  )
}


export const getServerSideProps = async ({ params }) => {
  // Disable on server side if feature isn't enabled
  const cmsEnabled = hasFeature("cms");
  if (!cmsEnabled) return { notFound: true };

  const client = setupContentful(true);
  const article = (
    await client.getEntries<TypeArticleSkeleton, "en-GB">({
      content_type: "article",
      "fields.slug[in]": params.slug,
    })
  )?.items[0];
  // 404 if no article was found
  if (!article) return { notFound: true };
  return {
    props: {
      article,
    },
  };
};
```

**Comment by YvesRijckaert** [comment]
In your component `BlogArticle`, you're not using the `articleUpdated` in your JSX. Can you try updating it to this:

```
export default function BlogArticle({
  article,
}){
  const articleUpdated = useContentfulLiveUpdates(article);
  
  return (
    <>
      <h1>{articleUpdated?.fields.title || ''}</h1> // you have to use articleUpdated here instead of article
    <>
  )
}
```

**Comment by Hultner** [comment]
> In your component `BlogArticle`, you're not using the `articleUpdated` in your JSX. Can you try updating it to this:
> 
> ```js
> export default function BlogArticle({
>   article,
> }){
>   const articleUpdated = useContentfulLiveUpdates(article);
>   
>   return (
>     <>
>       <h1>{articleUpdated?.fields.title || ''}</h1> // you have to use articleUpdated here instead of article
>     <>
>   )
> }
> ```

I still get the same exceptions as in the first entry here and no live updates.
To make it somewhat usable I built a custom hook instead which waits for ENTRY_SAVED MessageEvent and soft reloads the `getServerSideProps` via `router.replace(router.asPath)`. I tried also reloading on ENTRY_UPDATE but it looks like the API still responds with stale data in that case so I reverted to only listen on ENTRY_SAVED. This is not ideal but better then manual refresh or a full hard reload of the page. I still need to use the SDK context wrapper to initialise the client.

```tsx
import { useEffect } from "react";
import { useRouter } from "next/router";

/**
 * This hook is used to refresh the page when the live preview is updated.
 * Using the live preview SDK, did not work as expected.
 * A bit more naïve approach, but it works although slower.
 * Built API to be compatible with the live preview SDK,
 * so it can be easily replaced in the future.
 */

export default function usePreview<ContentData>(
  data: ContentData
): ContentData {
  const router = useRouter();

  useEffect(() => {
    const refreshOnLivePreview = (event: MessageEvent) => {
      if (event?.data?.from !== "live-preview") return;
      // Refresh only on saved update
      if (
        // event?.data?.action === "ENTRY_UPDATED" ||
        event?.data?.action === "ENTRY_SAVED"
      ) {
        // router.replace will only reload the server side props and not the whole page.
        // https://nextjs.org/docs/api-reference/next/router#routerreplace
        // https://www.joshwcomeau.com/nextjs/refreshing-server-side-props/
        router.replace(router.asPath);
      }
    };
    window.addEventListener("message", refreshOnLivePreview);

    return () => {
      window.removeEventListener("message", refreshOnLivePreview);
    };
  });
  return data;
}
```

**Comment by YvesRijckaert** [comment]
I tried to run the next-js example with REST and it seems to work fine on my end.
If you can provide me with a reproduceable example on codesandbox, I will be able to help you further :)

**Comment by Hultner** [comment]
> I tried to run the next-js example with REST and it seems to work fine on my end. If you can provide me with a reproduceable example on codesandbox, I will be able to help you further :)

Could it be something with my contenful account somehow?

I tried with codesandbox again but it's just not cooperating with me
<img width="549" alt="image" src="https://github.com/contentful/live-preview/assets/2669034/9f453021-6ced-4cda-baac-86533d707490">

**Comment by bgonzalez-thestable** [comment]
Hello!

I'm having the same issue. Is this maybe CORS related?

**Comment by bgonzalez-thestable** [comment]
Confirmed: this is due to CORS.

I was testing using my localhost (HTTP) but after setting up a self-signed SSL certificate I was able to get the callbacks working over HTTPS.

**Comment by Hultner** [comment]
@YvesRijckaert I ran my tests deployed on vercel with https so it shouldn’t be that in my case.

**Comment by Hultner** [comment]
@YvesRijckaert I ran my tests deployed on vercel with https so it shouldn’t be that in my case.

**Comment by bgonzalez-thestable** [comment]
@Hultner HTTPS or not, maybe it's still CORS issue?

**Comment by Hultner** [comment]
I didnt see any cors problems in my end, the actual payloads are received
(my own hook uses them) so the data is transmitted. I set up all the vercel
headers including the frame ones the same way as in the official examples.
