### ISSUE TITLE
live preview works but not on all fields

### ISSUE THREAD

**Issue by arantebw** [contentful/live-preview#328]
**Describe the bug**

The live preview works on almost all of the content's fields that we're trying to update. Those fields being updated are not published.

**To Reproduce**

Open a content with live preview running in localhost.

**Expected behavior**

Live preview is updating the content in preview mode even though the updated content is not yet published.

**Context (please complete the following information):**
 - Live preview SDK version number: `@contentful/live-preview": "^2.7.0"`
 - GraphQL API

**Comment by YvesRijckaert** [comment]
Hi @arantebw Thank you for submitting this bug report.
We would need some more detail and a reproduce able example to help you further. You can use codesandbox, codepen, or any other related tool.
Also describe which fields are not working? How to reproduce? etc...

Thank you!

**Comment by arantebw** [comment]
> We would need some more detail and a reproduce able example to help you further. You can use codesandbox, codepen, or any other related tool.

Does it mean I need to create a mock web app and contentful account?

**Comment by arantebw** [comment]
> Also describe which fields are not working? How to reproduce? etc...

As far as our use case goes, we found no specific field types that is expected not to work. For a example, a field type which contains a YouTube ID (short text) is not working while a hero section with a welcome message (short text) is working just fine.

**Comment by YvesRijckaert** [comment]
Please just create a simple project that reproduces the issue that you are describing. This way we will have more context over what the issue is and help you further 👍

**Comment by YvesRijckaert** [comment]
Need more context and reproducible example.
