### ISSUE TITLE
The Edit button in the live preview doesn't appear

### ISSUE THREAD

**Issue by Vlas1414** [contentful/live-preview#362]
I have a problem with the Edit button in the live preview. It doesn't appear on my hosted site but works locally

The only difference that I noticed between the hosted and local sites is the Error:
Uncaught Error: Minified React error #418; visit https://reactjs.org/docs/error-decoder.html?invariant=418 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

### Hosted site:
![image](https://github.com/contentful/live-preview/assets/57534169/6df33574-3759-4f26-bec6-41ba49a399ac)

### Localhost:
![image](https://github.com/contentful/live-preview/assets/57534169/c5fcf5b5-1233-4eef-80d2-6fa9dfbf8ecd)

 - Live preview SDK version number: 2.11.3
 - GraphQL API

**Comment by chrishelgert** [comment]
Hey 👋 
The edit button would not show up if some of the information is missing (e.g. entryId or fieldId) - can you check if that information is showing up in your DOM?
Is there a Link that you can share to check it out?
You can also enable the debug mode, do you some additional messages then in your browser console?

**Comment by Vlas1414** [comment]
@chrishelgert Hi 👋, thanks for the quick response!

Yes, I see entryId and fieldId in the DOM

![image](https://github.com/contentful/live-preview/assets/57534169/d0451fa9-9adb-4eeb-8347-46c2865a192c)

Here is the link to article
https://laviecal.com/api/draft?secret=Uf0dqao4JeQKmJ3gWG05gxa907NhLDgK&slug=/vital-bei/besondere-ernahrung-bei-krebserkrankungen

About `Uncaught Error: Minified React error #423; visit` error, looks like it isn't from the Contentful side.

### Messages in the browser console
```
Send message
{
    "action": "CONNECTED",
    "connected": true,
    "tags": 22,
    "taggedElementCount": 22,
    "locale": "de",
    "isInspectorEnabled": true,
    "isLiveUpdatesEnabled": true,
    "method": "CONNECTED",
    "from": "live-preview",
    "source": "live-preview-sdk",
    "location": "https://laviecal.com/vital-bei/besondere-ernahrung-bei-krebserkrankungen",
    "version": "2.11.3"
}
```
```
Received message
{
    "isInspectorActive": true,
    "action": "INSPECTOR_MODE_CHANGED",
    "method": "INSPECTOR_MODE_CHANGED",
    "from": "live-preview",
    "source": "live-preview-editor"
}
```

Error: `Live Updates requires the "sys.id" to be present on the provided data` (there are sys.id, strange error)

```
Send message
{
    "message": "Failed to subscribe",
    "payload": {
        "isGQL": false,
        "isValid": false,
        "sysId": null,
        "isREST": false
    },
    "type": "SUBSCRIPTION_SETUP_FAILED",
    "method": "ERROR",
    "from": "live-preview",
    "source": "live-preview-sdk",
    "location": "https://laviecal.com/vital-bei/besondere-ernahrung-bei-krebserkrankungen",
    "version": "2.11.3"
}
```

```
Send message
{
    "action": "SUBSCRIBED",
    "type": "GQL",
    "locale": "de",
    "entryId": "3Ci1b4Vlb590f92Dv36cCh",
    "event": "edit",
    "method": "SUBSCRIBED",
    "from": "live-preview",
    "source": "live-preview-sdk",
    "location": "https://laviecal.com/vital-bei/besondere-ernahrung-bei-krebserkrankungen",
    "version": "2.11.3"
}
```

**Comment by chrishelgert** [comment]
Mh I could be possible that due to the mismatch error, the tooltip gets removed from the DOM again.
Can you try finding your react errors and then check if the tooltip reappears?
I see it getting generated and then somehow removed again.
Thanks for sharing the Link, I removed the secret from your comment, but you should consider rotating this ;)
