### ISSUE TITLE
ContentfulLivePreviewProvider: toggling enableLiveUpdates prop causes errors

### ISSUE THREAD

**Issue by sami616** [contentful/live-preview#386]
When `false` is passed to the `enableLiveUpdates` prop initially, (and later updated to `true`) i see errors in the console saying that live updates weren't initialised properly which subsequently breaks live updates

```
Uncaught Error: Live updates are not initialized, please call `ContentfulLivePreview.init()` first.
```

**Comment by YvesRijckaert** [comment]
Can you help me understand this one a bit better, in which scenario would you change the value to true later on? Normally you would want to initially set this value to true for preview environments and false for your production environment. A minimal reproducible example with some more context will help
