### ISSUE TITLE
Output of useContentfulLiveUpdates always sets linked assets to have null values

### ISSUE THREAD

**Issue by sami616** [contentful/live-preview#397]
The output of this hook seems to always set any linked assets to the below despite the input having these fields defined. (obviously removing them from my preview anytime a live preview value changes)

```js
{
    "title": null,
    "description": null,
    "file": null
}
```

**Comment by YvesRijckaert** [comment]
Hi @sami616 could you create a minimum reproducible example and share some more details?
This should not happen

**Comment by sami616** [comment]
@YvesRijckaert and it doesn’t! My bad, make sure your locale is set right in your provider people! Thanks for your help.
