### ISSUE TITLE
Edit event on an entry with a rich text document has incorrect value when the rich text is emptied

### ISSUE THREAD

**Issue by prashantpalikhe** [contentful/live-preview#434]
**Describe the bug**
When an entry has a rich text, and the rich text is emptied. An edit event is triggered for the entry. But the updated entry passed to the callback still has the old rich text value.

**To Reproduce**
1. Go to live editor of an entry with a rich text field
2. Add some text to the rich text
3. Ensure that the data live updates
4. Remove the text from rich text
5. See the live update is now broken

**Expected behavior**
Updated entry should contain rich text with no data when the rich text is cleared

**Context (please complete the following information):**
 - Live preview SDK version number: 2.11.11
 - REST API

**Comment by skoch** [comment]
We are experiencing the same issue (with an older version: 2.4.4)

**Comment by YvesRijckaert** [comment]
Hi both, thanks for reaching out!
This bug is now fixed in the latest version
