### ISSUE TITLE
Why does useContentfulLiveUpdates return `null` for some empty fields

### ISSUE THREAD

**Issue by sami616** [contentful/live-preview#571]
This is more of a question than a bug report. 

When fetching data from the contentful api, empty or unpopulated fields dont get returned in the response. This is great imo because undefined is much nicer to work with than null values.

However, looking at `useContentfulLiveUpdates` this behaviour seems to be different, for example - deleting all text from a text input results in null being returned for that field

eg: `name: null`

However removing all references from a reference field results in the property not being returned at all.

Is there anyway to force the hook to *not* return unpopulated fields, or is this a design decision that i've overlooked?

**Comment by YvesRijckaert** [comment]
Hi, thank you for the issue :)
I am not aware of a specific design decision related to that, let me check in with the team. I'll create a ticket for it in the backlog to change that 👍
