### ISSUE TITLE
Rich text with embedded entries are not updated

### ISSUE THREAD

**Issue by Swaxer** [contentful/live-preview#586]
**The bug**
I know that Gatbsy support is under development. But I'm having a hard time finding out what's actually an issue and what's just wrong on my side. 

One strange behaviour I have found is that paragraphs are updated correctly while editing rich text. But no fields are send for embedded components. 

```js
export default ({ data }) => {
  const {
    contentful_id,
    heading,
    preamble,
    content: { json }
  } = data.contentfulArticlePage
  ```
So for this model, live updates works for the heading and also the json. Unless there is an embedded entry in the json.
With live updates used like this 
```js
  const updatedPost = useContentfulLiveUpdates({
    ...data.contentfulArticlePage,
    sys: { id: contentful_id }
  })

```
Below is when I log `updatedPost.content.JSON` and the actual json  from contentful how it should look.
![Screenshot 2024-02-20 at 16 18 26](https://github.com/contentful/live-preview/assets/6900003/1bcd7bf9-e3cc-4b62-b7b5-07c736080449)

**Context (please complete the following information):**
 - Live preview SDK version number: 2.17.2
 - Gatsby 3.10.0
 - "@contentful/rich-text-react-renderer": "^15.0.0",

I've been trying to follow #215 but without success. 
The error I get is this, which makes sense since it's during the live preview it can't find the necessary fields.
![Screenshot 2024-02-20 at 16 35 08](https://github.com/contentful/live-preview/assets/6900003/4af5b099-1d78-4aa3-b454-0b931a0e7bf0)

I don't need to be able to edit the embedded component (would be nice) but not criteria for me now. I've also had issues with the inspection tools which also only works when I build the webpage on localhost, not in production, but again not my main issue 👀

**Comment by YvesRijckaert** [comment]
Hi, thanks for your issue!
We are aware of a lot of issues with Gatsby and the LP SDK. The main issue being that `gatsby-source-contentful` transforms the data differently than our official REST / GraphQL API. A requirement to work with the LP SDK is that the data should **not** be transformed, which is what the `gatsby-source-contentful` plugin does. If you really want to have support for live updates, then one workaround is to not use this plugin and fetch data directly from our APIs.
Inspector mode should work correctly with Gatsby.

We hope to add support for Gatsby at some point, and have tickets for it in our backlog
