### ISSUE TITLE
Problem with contenful-live-preview

### ISSUE THREAD

**Issue by PatrykMaternicki** [contentful/live-preview#602]
**To Reproduce**
1. Create entity with nested entity.
2. Save.
3. Change something in nested entity but don't save. 
4. Return to root
5. Create another one contentType (i doesn't matter what a type)
6. Move position
7. Previous state of data has return not a new.

**Expected behavior**
Should be return a new state of data.

**Screenshots / example**
https://file.io/uK4qieYOPCZu

When I run preview mode in mode application, evrything is working.

**Context (please complete the following information):**
 - Live preview SDK version number: 2.7.13
 - REST
 
**Additional context**
I use vanilia contenful-preview with Nuxt.

**Comment by chrishelgert** [comment]
Hey,
thanks for reporting the issue
We are aware of this one, and there will be a fix soon :)

**Comment by PatrykMaternicki** [comment]
Tell me when I able to check it :)

**Comment by skoch** [comment]
Happening for us as well. (2.4.4)
Please let us know when a fix is ready, this is critical (for us).

**Comment by YvesRijckaert** [comment]
Hi all, we will release this soon. If you want to try it out already you can install the alpha release of the SDK: [@contentful/live-preview@3.0.0-alpha.24](https://github.com/contentful/live-preview/releases/tag/%40contentful%2Flive-preview%403.0.0-alpha.24)
