### ISSUE TITLE
vannila-js parcel-bundler deprecated 

### ISSUE THREAD

**Issue by jagadeeshgade008** [contentful/live-preview#608]
Currently, we are using https://www.npmjs.com/package/parcel-bundler for vanilla JS live preview, but it is deprecated. consider modifying the dependency to Vite. Please have a look at the following URL for more information: https://vitejs.dev/guide/.

**Comment by YvesRijckaert** [comment]
Hey! Thank you for reporting this.
Feel free to open a PR to contribute, will close this issue for now 🙏
