### ISSUE TITLE
Live Updates stop working if fallback is used

### ISSUE THREAD

**Issue by marlonschlosshauer** [contentful/live-preview#682]
**Describe the bug**
If any field that gets passed into `useContentfulLiveUpdates` has a fallback to another locale (that is actively used), then all live-updates for that usage of the hook are bricked.

**To Reproduce**
1. Setup two locales for your environment, with one having a fallback to the other (e.g DE falling back to EN)
2. Create a Content-Type with two fields (e.g text image with headline & content)
3. Create an entry of that CT, where for the fallback locale (e.g EN) both fields have data (e.g headline: "test", content: "test 2")
4. Add data to one (and only one!) of the fields (e.g headline) on that entry for the non-fallback target locale (e.g DE)
5. Open the preview in the non-fallback target locale (e.g DE) & change the field that has data in both locales
6. No update happens
7. Add content to the field that uses the fallback (e.g "content")
8. Updates on the other field (not using the fallback) begin to work

Reloading the preview / page causes the update to show up, too.

**Expected behavior**
I would've expected for the field to update with the new value, irregardless if a fallback is used or not. 

**Screenshots / example**

https://github.com/contentful/live-preview/assets/24259317/590f6715-8d56-4e7e-a87f-e74b92f93eeb

Here is a minimal repro, which is essentially just what the Next installation in the README asks for: https://github.com/marlonschlosshauer/contentful-live-update-sanity-check

Quick overview:
- 1x API route to activate draft mode and redirect 
- 1x page to render a demo block for the preview
- Layout file contains a client component with the ContentfulLivePreviewProvider 
- The page itself fetches a specific (test) entry (with getEntries to receive the Contentful metadata)
- Data is passed straight into a (client) component with `useContentfulLiveUpdates`

**Context (please complete the following information):**
 - Live preview SDK version number: 3.0.2 (also happens with 2.17.0)
 - REST 
 - Next 14.2 (also happens on 14.0)

**Additional context**
 - Draft mode is successfully activated
 - Preview indicates that both the inspector (which works!) and live updates are enabled
 - Contentful Debug shows that `ENTRY_SAVED` is received 
 - In our space the `de` locale (which is used to demo here) has a fallback to `en`
 - I found this issue which talks about a similar (same?) issue: https://github.com/contentful/live-preview/issues/140

**Comment by 2wce** [comment]
hi @marlonschlosshauer thank you for the detailed issue 🙏🏽we will look into this & post an update here once we have a fix/timeline for a fix

**Comment by chrishelgert** [comment]
Hi @marlonschlosshauer,
We deployed an fix for the issue on our Side, you don't have to bump the SDK version :) 
Note: The issue was not related to the fallback it was a missing reference that was not handled correctly during the live updates.
