### ISSUE TITLE
Setting up Vercel live preview webhook

### ISSUE THREAD

**Issue by jonrrivera** [contentful/live-preview#689]
Hi,

I have been implementing this revalidation feature from the [next js app route example](https://github.com/contentful/live-preview/tree/main/examples/next-app-router). I have correctly set up the api routes to enable, disable and revalidate draft mode. But currently having an issue setting up the [Webhook in Vercel ](https://github.com/contentful/live-preview/tree/main/examples/next-app-router#step-6-deploy-on-vercel)  because I keep getting this issue. I am making sure the `CONTENTFUL_REVALIDATION_SECRET` is correct but unfortunately I `/api/revalidate` seems to not be getting any path or slug from the payload. Please see more here. 

Hope someone can help, thank you!

<img width="1534" alt="Screenshot 2024-04-23 at 8 49 41 PM" src="https://github.com/contentful/live-preview/assets/18686388/7f0eefac-9681-4ffc-b6c3-b53c504e072e">

**Comment by YvesRijckaert** [comment]
Hi! 
Can you share your code? What did you change compared to the example?
