### ISSUE TITLE
Received an update for an unknown subscription 

### ISSUE THREAD

**Issue by bobslaede** [contentful/live-preview#704]
**Describe the bug**
Nextjs 14  
Headers for sameorigin  
`@contentful/live-preview v3.3.2`  
Using live preview many events are sent and received, but updates to content is not.   
Error in console `Received an update for an unknown subscription`  
The error contains the actual data that has changed, but it doesn't get passed to the 

**To Reproduce**
1. Go to some content and click live preview
2. Change something

**Expected behavior**
Expect content to find its way to the `useContentfulLiveUpdates` hook  

**Screenshots / example**
![Screenshot from 2024-05-02 10-26-59](https://github.com/contentful/live-preview/assets/437918/b12cdf37-88c1-4a3a-9004-77bd9ec99257)

**Context (please complete the following information):**
 - Live preview SDK version number: 3.3.2
 - REST / GraphQL API rest

**Additional context**

**Comment by 2wce** [comment]
hi @bobslaede thank you for using the Live Preview SDK, I'm sorry you are facing this issue. Do you have a minimal reproducible example that I can take a look at to debug this further?

**Comment by bobslaede** [comment]
Sorry I dont have that. Im currently migrating a project from another CMS to contentful. 
We are a paying customer, and I wouldnt mind doing a zoom with you if that could help. My timezone is CEST :)

**Comment by bobslaede** [comment]
Another content type that I have, actually works. Same setup and configuration. Different view and content type.

**Comment by 2wce** [comment]
hi @bobslaede In that case if you don't mind opening a support [ticket](https://support.contentful.com/hc/en-us/requests/new) for this we can prioritise & investigate the issue better since we'll be able to impersonate your account (_with your permission of course_) & schedule a call if need be 😊
