### ISSUE TITLE
Compatibility with Next.js 15 and React 19

### ISSUE THREAD

**Issue by catchergeese** [contentful/live-preview#778]
**Describe the bug**
`@contentful/live-preview` throws an error in Next.js 15 (RC) and React 19 (RC).

**To Reproduce**
1. Setup project with Next.js version 15 with React 19
2. Follow @contentful/live-preview docs for Next.js integration
3. Run `npm run dev` to run dev server
4. See error `TypeError: Cannot read properties of undefined (reading 'ReactCurrentDispatcher')`

**Expected behavior**
It works.

**Context (please complete the following information):**
 - Live preview SDK version number: 4.2.3

**Additional context**
@contentful/live-preview limits React's version to 18.
I built the package locally after removing this restriction and the error is gone (but I didn't test it in-and-out).

**Comment by KlotzJesse** [comment]
Can be fixed by correctly stop bundeling react into the packages, by changing the external option in vite.config to:
`external: ["react", /^react\/.*/, "react-dom", /react-dom\/.*/],`

**Comment by YvesRijckaert** [comment]
Issue should be fixed with the newest version: [4.5.17](https://github.com/contentful/live-preview/compare/@contentful/live-preview@4.5.16...@contentful/live-preview@4.5.17)

**Comment by YvesRijckaert** [comment]
Reopening as there seemed to have been some issues with older versions of Next / React with this change 😓

**Comment by YvesRijckaert** [comment]
Fixed with latest release 🙏
