### ISSUE TITLE
Can't import the named export 'version' (imported as 'version') from default-exporting module (only default export is available) v4.3.1

### ISSUE THREAD

**Issue by tobslob** [contentful/live-preview#822]
Can't import the named export 'version' (imported as 'version') from default-exporting module (only default export is available)

This issue now exist on version 4.3.1, and the latest version 4.4.1 after deleting node-modules and reinstall.

"@contentful/live-preview": "^4.3.1",

<img width="913" alt="image" src="https://github.com/user-attachments/assets/a5f12134-c07b-4223-9514-efbc4682f2cc">

**Comment by 2wce** [comment]
thanks for reporting this @tobslob,  this should be working in version 4.5.0 now 🚀
