### ISSUE TITLE
React incompatible with current and previous versions

### ISSUE THREAD

**Issue by danielmariz** [contentful/live-preview#869]
**Describe the bug**
I'm trying implementing the package in a Next JS project with current versions `"@contentful/live-preview": "^4.5.5",`, `"next": "^14.2.4"` and `"react": "^18.3.1",` using next app router structure and setting the live preview provider in the global layout like described in the documentation.

```
export default function Template({ children }: { children: React.ReactNode; pageProps: any }) {
    const isPreview = draftMode().isEnabled
    return (
        <ContentfulLivePreviewProvider
            locale='en-US'
            enableInspectorMode={isPreview}
            enableLiveUpdates={isPreview}
            debugMode={isPreview}>
            <div className={`${teodorFont.variable} font-sans`}>
                {children}
                <Animate />
            </div>
        </ContentfulLivePreviewProvider>
    )
}
```

But getting a runtime error:
<img width="981" alt="Screenshot 2024-09-06 at 10 41 38" src="https://github.com/user-attachments/assets/36e5b016-cb38-4d55-b9dd-28b15b48b35b">

When trying do downgrade to previous version `"@contentful/live-preview": "^4.4.2",` I'm getting this error.

<img width="987" alt="image" src="https://github.com/user-attachments/assets/56b52e5d-9882-4067-a586-16337734544b">

If I remove the provider than preview works in a new tab.

**To Reproduce**
1. Setup a next project with react version as described
2. Add the live preview provider in the layout app structure
3. setup your draft route

**Expected behavior**
Get the page running in the live preview iframe in contentful

**Screenshots / example**
If applicable, add screenshots to help explain your problem. Please also submit a minimal reproducible example to help with the investigation. Feel free to use CodeStandbox or any other similar service of your choosing.

**Context (please complete the following information):**
 - Live preview SDK version number: 4.5.5 or 4.4.2
 - REST API

**Additional context**
When removing live preview I'm able to test the integration with contentful by previewing it in a new tab

**Comment by chrishelgert** [comment]
👋 
Do you have "use client" on your Template?
The context is only available on client components

**Comment by danielmariz** [comment]
> 👋 Do you have "use client" on your Template? The context is only available on client components

Actually not, I will refactor and test it again.
Thanks

**Comment by danielmariz** [comment]
Moving it to a client component fixed all issues, just don't think it clear on the next config documentation that is required to be only in a client component
