### ISSUE TITLE
Better Typescript support for Content Source Maps

### ISSUE THREAD

**Issue by asgorobets** [contentful/live-preview#924]
**Describe the bug**
Currently encodeGraphQLResponse function will accept a GraphQLResponse object and return a GraphQLResponse type as well. Most Typescript usage of GraphQL will want to benefit from GraphQL Typed responses, like with libraries like https://gql-tada.0no.co/. Currently GraphQLResponse will be helpful to validate "extensions" field, but should not override the "data" property type.

Ideally if encodeGraphQLResponse can use a type predicate and augment it (intersect?) with extensions field, that would preserve the original response type and let the encoder do it's thing.

GraphQL responses come in different flavors, for example urql uses OperationResult type that returns all the usual suspects (data, extensions, operation, etc), as long as a response has extensions and data fields, it should be acceptable as an input for encoding.
https://spec.graphql.org/October2021/#sec-Response-Format

**Comment by YvesRijckaert** [comment]
Thanks for catching that :) fixed as part of the latest release 🎉
