### ISSUE TITLE
Enable live preview and auto-refresh on a next 13 app without the SDK 

### ISSUE THREAD

**Issue by Fedeorlandau** [contentful/live-preview#93]
Hello there, how are you?

I'd like to share something that can be useful for people with a setup like ours.

We have a Next 13 app that uses a BFF for fetching the content from the CMS. Due to this, we don't have the contentful sdk on the FE code so we came up with the following rudimentary approach.

`components/Preview/Preview.tsx`
```tsx
"use client";
import React, { useEffect } from "react";
import { useRouter } from "next/navigation";

function Preview() {
  const router = useRouter();

  useEffect(() => {
    const checkLivePreview = (event: any) => {
      if (typeof event.data !== "object" || !event.data) return;
      if (event.data.from !== "live-preview") return;

      router.refresh();
    };
    window.addEventListener("message", checkLivePreview);

    return () => {
      window.removeEventListener("message", checkLivePreview);
    };
  });

  return <></>;
}

export default Preview;
```

Then you can call `<Preview/>` from your layout.tsx file.

This code adds an event listener that it's waiting for any 'live-preview' event. This code will refresh the page automatically when you change something in the contentful live preview editor. 

Please keep in mind this still requires that you point your preview URL to an API that can handle the preview content delivery api from Contentful.

Contentful team, do you see any issues with this approach? So far it's working fine (just a little bit of delay between the auto-save and the refresh)

Regards,

**Comment by chrishelgert** [comment]
Hey,
are you also transforming the data on your server side?
If not it should be still possible to use the SDK to receive the updates, as it only depends on the data structure, and not on the contentful-client directly.
If the data gets transformed, this should work out really well (only caveat is the small delay between editing and updating).
Thanks for sharing
