### ISSUE TITLE
@contentful/rich-text-react-renderer Inspector edit button not shown since 4.5.7 release

### ISSUE THREAD

**Issue by volodyad** [contentful/live-preview#943]
@contentful/rich-text-react-renderer v 16.0.0 - in preview Edit button not shown

 - Live preview SDK version number: [e.g.  4.5.7] on version 4.5.6 works fine
@contentful/rich-text-react-renderer 
Attributes are added and they work on version 4.5.6

```
<div data-contentful-field-id="body" data-contentful-entry-id="id"> 
content
 </div>
```

**Comment by z0al** [comment]
Hey @volodyad, thanks for the report. 

Would you mind updating to the latest version (v4.5.14 as of now) and report back. Looking at the change log there were a few bug fixes since 4.5.7.

**Comment by volodyad** [comment]
I have tried all of them from 4.5.14 to 4.5.7, actually it seems it related to https://github.com/contentful/live-preview/issues/942 as element overlapping change was introduced exaclty in 4.5.7

**Comment by YvesRijckaert** [comment]
Issue should be fixed as part of this release: https://github.com/contentful/live-preview/releases/tag/%40contentful%2Flive-preview%404.5.15

**Comment by volodyad** [comment]
Issue is still reproduces on version 4.5.16
