### ISSUE TITLE
Bug Report: Live Editing Fails for Some Pages, Causes Infinite Loading and Crashes

### ISSUE THREAD

**Issue by yashodhan271** [contentful/live-preview#954]
### **Description:**

I have successfully implemented draft mode and live preview for my project. However, when I try to use live editing on certain pages, it doesn't work as expected. The live editor works fine for other pages, but on a few specific articles/pages, the following issues occur:

Live Editor Not Functioning: For specific pages, the live editing feature does not activate, and changes are not reflected in real time.

Page Crashes: In some cases, opening certain articles/pages results in the page crashing when attempting to use the live editor.

Infinite Loading on Save/Refresh: When attempting to save or refresh the page, the system enters an infinite loading state. The page never saves, and no changes are applied.

### **Steps to Reproduce:**

Implement draft mode and live preview on the project.
Open and edit various pages (including those with issues).
Attempt to use the live editor on problematic pages.
Observe that the editor does not work, and in some cases, the page crashes or goes into infinite loading.

### **Expected Behavior:**

The live editor should work for all pages.
Saving and refreshing should function as expected without causing infinite loading.
Pages should not crash when attempting to use the live editor.

### **Actual Behavior:**

Live editor fails to work on certain pages.
Some pages crash when live editing is initiated.
Infinite loading occurs when trying to refresh or save changes.

**Comment by YvesRijckaert** [comment]
hi @yashodhan271
Thanks for submitting this bug report. Unfortunately we would need some more information and a minimal reproducible example to be able to properly debug this.
