### ISSUE TITLE
@contentful/rich-text-react-renderer Inspector edit button not shown since 4.5.7 release

### ISSUE THREAD

**Issue by volodyad** [contentful/live-preview#973]
@contentful/rich-text-react-renderer v 16.0.0 - in preview Edit button not shown

Live preview SDK version number: [e.g. 4.5.16] on version 4.5.6 works fine
@contentful/rich-text-react-renderer
Attributes are added and they work on version 4.5.6

```
<div data-contentful-field-id="body" data-contentful-entry-id="id"> 
content
 </div>
```

To reopen https://github.com/contentful/live-preview/issues/943
as fix didn't help

**Comment by YvesRijckaert** [comment]
@volodyad can you provide a minimal reproducible example please?

**Comment by volodyad** [comment]
I will try in some time, do not have time yet, but it is just simple page and rich text on it

**Comment by YvesRijckaert** [comment]
Hi @volodyad can you check again? The issue should be fixed now.
